# Generated by Django 4.2.7 on 2026-06-07 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
                (
                    "slug",
                    models.SlugField(
                        choices=[
                            ("gratuito", "Gratuito"),
                            ("basico", "Básico"),
                            ("premium", "Premium"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "max_whatsapp",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Máx. WhatsApp"
                    ),
                ),
                (
                    "max_respostas",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="0 = ilimitado",
                        verbose_name="Máx. Respostas Automáticas",
                    ),
                ),
                (
                    "permite_horario",
                    models.BooleanField(
                        default=False, verbose_name="Permite Horário de Atendimento"
                    ),
                ),
                (
                    "permite_boas_vindas",
                    models.BooleanField(
                        default=True, verbose_name="Permite Mensagem de Boas-Vindas"
                    ),
                ),
                (
                    "preco_mensal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Preço Mensal (R$)",
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("ordem", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Plano",
                "verbose_name_plural": "Planos",
                "ordering": ["ordem"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("suspenso", "Suspenso"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="ativo",
                        max_length=20,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "data_vencimento",
                    models.DateField(verbose_name="Data de Vencimento"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assinaturas",
                        to="subscriptions.plan",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Assinatura",
                "verbose_name_plural": "Assinaturas",
            },
        ),
    ]
