# Generated by Django 4.2.30 on 2026-08-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaktoWebhookLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=80)),
                ("payload", models.JSONField(default=dict)),
                ("processado", models.BooleanField(default=False)),
                ("detalhe", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Log Webhook Cakto",
                "verbose_name_plural": "Logs Webhook Cakto",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.AddField(
            model_name="subscription",
            name="cakto_customer_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="E-mail Cakto"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="cakto_last_event",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="Último evento Cakto"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="cakto_order_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Último pedido Cakto"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="cakto_subscription_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Assinatura Cakto"
            ),
        ),
    ]
