# Generated by Django 4.2.7 on 2026-06-07 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("conectado", "Conectado"),
                            ("desconectado", "Desconectado"),
                            ("aguardando_qr", "Aguardando QR Code"),
                            ("conectando", "Conectando"),
                        ],
                        default="desconectado",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "numero_telefone",
                    models.CharField(blank=True, max_length=20, verbose_name="Número"),
                ),
                (
                    "nome_perfil",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nome do Perfil"
                    ),
                ),
                (
                    "qr_code",
                    models.TextField(blank=True, verbose_name="QR Code (base64)"),
                ),
                (
                    "conectado_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Conectado em"
                    ),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_connection",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Conexão WhatsApp",
                "verbose_name_plural": "Conexões WhatsApp",
            },
        ),
        migrations.CreateModel(
            name="Mensagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direcao",
                    models.CharField(
                        choices=[("recebida", "Recebida"), ("enviada", "Enviada")],
                        max_length=10,
                        verbose_name="Direção",
                    ),
                ),
                ("conteudo", models.TextField(verbose_name="Conteúdo")),
                (
                    "telefone_origem",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone Origem"
                    ),
                ),
                (
                    "telefone_destino",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone Destino"
                    ),
                ),
                (
                    "contato_nome",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nome do Contato"
                    ),
                ),
                (
                    "tipo_resposta",
                    models.CharField(
                        blank=True,
                        help_text="palavra_chave, boas_vindas, fora_horario, manual",
                        max_length=30,
                        verbose_name="Tipo de Resposta",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensagens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensagem",
                "verbose_name_plural": "Mensagens",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ContatoAtendido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telefone", models.CharField(max_length=20)),
                ("primeira_mensagem_em", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contatos_atendidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contato Atendido",
                "verbose_name_plural": "Contatos Atendidos",
                "unique_together": {("user", "telefone")},
            },
        ),
    ]
