# Generated by Django 4.2.7 on 2026-06-07 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoHorario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hora_inicial",
                    models.TimeField(default="08:00", verbose_name="Hora Inicial"),
                ),
                (
                    "hora_final",
                    models.TimeField(default="18:00", verbose_name="Hora Final"),
                ),
                (
                    "mensagem_fora_horario",
                    models.TextField(
                        default="Nosso atendimento funciona das 08:00 às 18:00.",
                        verbose_name="Mensagem Fora do Horário",
                    ),
                ),
                ("ativo", models.BooleanField(default=False, verbose_name="Ativo")),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_horario",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Horário",
                "verbose_name_plural": "Configurações de Horário",
            },
        ),
        migrations.CreateModel(
            name="ConfiguracaoBoasVindas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ativo", models.BooleanField(default=False, verbose_name="Ativo")),
                (
                    "mensagem",
                    models.TextField(
                        default="Olá! Seja bem-vindo.\nDigite:\n1 - Vendas\n2 - Suporte\n3 - Financeiro",
                        verbose_name="Mensagem",
                    ),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_boas_vindas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Boas-Vindas",
                "verbose_name_plural": "Configurações de Boas-Vindas",
            },
        ),
        migrations.CreateModel(
            name="AutoResposta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "palavra_chave",
                    models.CharField(max_length=100, verbose_name="Palavra-chave"),
                ),
                ("resposta", models.TextField(verbose_name="Resposta")),
                (
                    "status",
                    models.CharField(
                        choices=[("ativa", "Ativa"), ("inativa", "Inativa")],
                        default="ativa",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="autorespostas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Resposta Automática",
                "verbose_name_plural": "Respostas Automáticas",
                "ordering": ["palavra_chave"],
                "unique_together": {("user", "palavra_chave")},
            },
        ),
    ]
