# Generated by Django 4.2.30 on 2026-06-07 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("autorespostas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoComportamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "atraso_segundos",
                    models.PositiveSmallIntegerField(
                        default=2,
                        help_text="Tempo de espera antes de enviar a autoresposta (0 a 60).",
                        verbose_name="Atraso antes de responder (segundos)",
                    ),
                ),
                (
                    "mostrar_digitando",
                    models.BooleanField(
                        default=True,
                        help_text="Exibe o indicador de digitação no WhatsApp antes de responder.",
                        verbose_name="Mostrar 'digitando...'",
                    ),
                ),
                (
                    "atraso_aleatorio",
                    models.BooleanField(
                        default=False,
                        help_text="Adiciona de 1 a 5 segundos extras ao atraso configurado.",
                        verbose_name="Variar tempo aleatoriamente",
                    ),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_comportamento",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Comportamento",
                "verbose_name_plural": "Configurações de Comportamento",
            },
        ),
    ]
